### ISSUE TITLE
Unable to get application project no in the dashboard

### ISSUE THREAD

**Issue by arunabhabanerjee** [kevchu3/openshift4-grafana#2]
Hi,

I am unable to get the application project details in the dashboard. It seems the below query has some problems.

count(kube_namespace_created{namespace!~"(default|kube|openshift).*"})

OpenShift Version 4.6

Thank you.

**Comment by kevchu3** [comment]
Thank you for your contributions, I've fixed the query to the following: `count(kube_namespace_labels{namespace!~"(default|kube|openshift).*"})`

**Comment by arunabhabanerjee** [comment]
Thanks a lot.
