### ISSUE TITLE
How to get right available cores

### ISSUE THREAD

**Issue by arunabhabanerjee** [kevchu3/openshift4-grafana#4]
Hi,

In our environment, we have three types of nodes, Master. Infra and Worker. If we want to get the cores details only for worker nodes (except master and infra) then how we can do it. I tried many options but it's still calculating infra node cores, but we already configure infra node is "non-schedule" like master node.

The actual query:

sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!="master"})

Node output:

`NAME                        STATUS   ROLES    AGE     VERSION
perf-kl5cc-infra-0-88msw    Ready    infra    3d8h    v1.19.16+35fca9a
perf-kl5cc-infra-0-j5n5t    Ready    infra    3d8h    v1.19.16+35fca9a
perf-kl5cc-master-0         Ready    master   3d13h   v1.19.16+35fca9a
perf-kl5cc-master-1         Ready    master   3d13h   v1.19.16+35fca9a
perf-kl5cc-master-2         Ready    master   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-4zr6m   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-6wmzf   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-9wrz8   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-f29px   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-flbjt   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-jkwlk   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-jl8x5   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-jw8tq   Ready    worker   3d13h   v1.19.16+35fca9a
perf-kl5cc-worker-0-xqq4l   Ready    worker   3d13h   v1.19.16+35fca9a`

Thank you.

**Comment by kevchu3** [comment]
This query should work for you:
`sum(cluster:capacity_cpu_cores:sum)-sum(cluster:cpu_core_node_labels{label_node_role_kubernetes_io_master="true"})-sum(cluster:cpu_core_node_labels{label_node_role_kubernetes_io_infra="true"})`

I'll go ahead and update my dashboards accordingly

**Comment by arunabhabanerjee** [comment]
I tried the above query and still, it shows the wrong data. 

I have 9 worker nodes with 16 cores, hence I am expecting 144 cores. But still it is showing 152 cores.

**Comment by arunabhabanerjee** [comment]
I tried this query and I got "no data"

sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io="worker"})

**Comment by arunabhabanerjee** [comment]
This is labels we have:

`Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=dpdkc16r64d120
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=regionOne
                    failure-domain.beta.kubernetes.io/zone=nova
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=perf-kl5cc-worker-0-4zr6m
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=
                    node.kubernetes.io/instance-type=dpdkc16r64d120
                    node.openshift.io/os_id=rhcos
                    topology.kubernetes.io/region=regionOne
                    topology.kubernetes.io/zone=nova`

**Comment by kevchu3** [comment]
Your query `sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io="worker"})` won't work because `cluster:capacity_cpu_cores:sum` only defines `label_node_role_kubernetes_io="master"` and not "worker", so you'll need to find a label from another metric to differentiate master, infra, and worker.

What does the query `cluster:cpu_core_node_labels` show?  You should be able to find a label to use to differentiate between the node types, and it's unclear to me why `label_node_role_kubernetes_io_master="true"` and `label_node_role_kubernetes_io_infra="true"` aren't providing the right counts.

**Comment by arunabhabanerjee** [comment]
I was able to get the actual worker core count using the below query:

`sum(cluster:capacity_cpu_cores:sum)-sum(cluster:cpu_core_node_labels{label_node_role_kubernetes_io_master="true"})-sum(cluster:cpu_core_node_labels{label_node_role_kubernetes_io_infra="true"})-8`

**Comment by kevchu3** [comment]
How do you account for the missing 8 cores?  Did you have a master or infra node mislabeled?

**Comment by arunabhabanerjee** [comment]
Yes, I had some issues. Now I noticed one more thing the below query is not showing any data. Could you please help?

`(cluster_operator_conditions{condition!~"Available|Upgradeable|RetrievedUpdates"} == 1)`

<img width="469" alt="image" src="https://user-images.githubusercontent.com/31511236/158731286-cf5554ca-df05-4b75-84ea-3db29ba624d4.png">

**Comment by kevchu3** [comment]
Does `cluster_operator_conditions` return anything useful?

**Comment by arunabhabanerjee** [comment]
yes. 

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/31511236/158731794-84f8c1d0-e342-4b80-89cd-b839cb793f91.png">

**Comment by arunabhabanerjee** [comment]
And the last one is from Infrastructure metrics. I don't see any data.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/31511236/158731977-c77c418a-c490-40b3-b2ae-f4db387b9b33.png">

**Comment by kevchu3** [comment]
Both those queries showing 0 means your cluster is in good shape.  They are alerting on any number > 0.  In the first query, you do not have any cluster operators in statuses other than Available, Upgradeable, or RetrievedUpdates.  In the second query, you do not have any nodes in NotReady, DiskPressure, MemoryPressure, or PIDPressure state.

**Comment by arunabhabanerjee** [comment]
Got it. Thanks for the explanation.

**Comment by kevchu3** [comment]
I'll go ahead and close this issue since your questions have now been resolved
